name: delivery
env:
  DH_REPO_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}"
  IMAGE_TAG: "${{ github.sha }}"

on:
  push:
    branches: [main]

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '14'

      - name: Build project
        run: mvn package -DskipTests=true

      - name: Build image and push it to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DH_REPO_NAME }}
          tags: ${{ env.IMAGE_TAG }},latest

      - name: Dispatch rolling update action
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ env.DISPATCH_REPO }}
          event-type: ${{ env.UPDATE_EVENT_TYPE }}
          client-payload: '{"service_name": "${{ env.SERVICE_NAME }}", "image_name": "${{ env.IMAGE_NAME }}"}'
        env:
          DISPATCH_REPO: "briana-crm/briana-deploy"
          UPDATE_EVENT_TYPE: "rolling_update"
          SERVICE_NAME: "briana_stack_${{ github.event.repository.name }}"
          IMAGE_NAME: "${{ env.DH_REPO_NAME }}:${{ env.IMAGE_TAG }}"
