name: test

on:
  pull_request:
    branches: [development]

jobs:
  test:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '14'

      - name: Run tests
        run: mvn test
